import * as React from 'react';
import TextBlock from './TextBlock';

/**
 * TextBlock Examples
 * 
 * Demonstrates different variants, alignments, and styling options
 * for the TextBlock component in SlaidAI presentations.
 */
export default function TextBlockExamples() {
  return (
    <div className="p-8 space-y-12 bg-white">
      
      {/* Variant Examples */}
      <section>
        <h2 className="text-2xl font-bold mb-6 text-gray-800">Text Variants</h2>
        <div className="space-y-6">
          
          <TextBlock variant="title">
            This is a Title
          </TextBlock>
          
          <TextBlock variant="heading">
            This is a Heading
          </TextBlock>
          
          <TextBlock variant="body">
            This is body text. It's perfect for longer paragraphs and detailed content in your presentations. The text is sized appropriately for readability across different devices.
          </TextBlock>
          
          <TextBlock variant="caption">
            This is a caption - smaller text for annotations, credits, or supplementary information.
          </TextBlock>
          
        </div>
      </section>

      {/* Alignment Examples */}
      <section>
        <h2 className="text-2xl font-bold mb-6 text-gray-800">Text Alignment</h2>
        <div className="space-y-4">
          
          <TextBlock variant="heading" align="left">
            Left Aligned Text (Default)
          </TextBlock>
          
          <TextBlock variant="heading" align="center">
            Center Aligned Text
          </TextBlock>
          
          <TextBlock variant="heading" align="right">
            Right Aligned Text
          </TextBlock>
          
        </div>
      </section>

      {/* Color Examples */}
      <section>
        <h2 className="text-2xl font-bold mb-6 text-gray-800">Text Colors</h2>
        <div className="space-y-4">
          
          <TextBlock variant="heading" color="text-blue-600">
            Blue Heading
          </TextBlock>
          
          <TextBlock variant="body" color="text-green-700">
            Green body text for emphasis or success messages.
          </TextBlock>
          
          <TextBlock variant="caption" color="text-gray-500">
            Muted caption text
          </TextBlock>
          
          <TextBlock variant="heading" color="text-red-500">
            Red text for warnings or errors
          </TextBlock>
          
        </div>
      </section>

      {/* Dark Background Examples */}
      <section className="bg-gray-900 p-6 rounded-lg">
        <h2 className="text-2xl font-bold mb-6 text-white">On Dark Backgrounds</h2>
        <div className="space-y-4">
          
          <TextBlock variant="title" color="text-white" align="center">
            White Title on Dark
          </TextBlock>
          
          <TextBlock variant="body" color="text-gray-100">
            Light body text that's readable on dark backgrounds. Perfect for modern slide designs with dark themes.
          </TextBlock>
          
          <TextBlock variant="caption" color="text-gray-300">
            Caption text with appropriate contrast
          </TextBlock>
          
        </div>
      </section>

      {/* AI-Generated Content Examples */}
      <section>
        <h2 className="text-2xl font-bold mb-6 text-gray-800">AI-Generated Content Examples</h2>
        <div className="space-y-6">
          
          {/* Slide 1 Example */}
          <div className="border border-gray-200 rounded-lg p-6">
            <TextBlock variant="title" align="center" color="text-blue-600">
              Benefits of Remote Work
            </TextBlock>
            
            <TextBlock variant="body">
              Remote work has transformed the modern workplace, offering unprecedented flexibility and opportunities for both employees and employers.
            </TextBlock>
            
            <TextBlock variant="caption" color="text-gray-500" align="right">
              Generated by SlaidAI
            </TextBlock>
          </div>

          {/* Slide 2 Example */}
          <div className="border border-gray-200 rounded-lg p-6 bg-purple-50">
            <TextBlock variant="heading" align="center" color="text-purple-800">
              Key Statistics
            </TextBlock>
            
            <TextBlock variant="body" color="text-purple-700">
              Companies using remote work report 25% higher employee satisfaction and 30% reduction in overhead costs.
            </TextBlock>
          </div>
          
        </div>
      </section>

      {/* Custom Styling Examples */}
      <section>
        <h2 className="text-2xl font-bold mb-6 text-gray-800">Custom Styling</h2>
        <div className="space-y-4">
          
          <TextBlock 
            variant="heading" 
            className="font-mono bg-yellow-100 p-4 rounded-lg border-l-4 border-yellow-500"
          >
            Custom styled heading with monospace font and background
          </TextBlock>
          
          <TextBlock 
            variant="body" 
            className="italic border border-dashed border-gray-300 p-3 rounded"
            color="text-indigo-600"
          >
            Italic body text with custom border and indigo color
          </TextBlock>
          
        </div>
      </section>

    </div>
  );
} 